//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.Blitz.ReportGenerator.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditRequests
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int OperatorClientId { get; set; }
        public int OperatorId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> UserClientId { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public int StateId { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Clients Clients1 { get; set; }
        public virtual CreditRequestStates CreditRequestStates { get; set; }
        public virtual Templates Templates { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
