//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.Blitz.ReportGenerator.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogins
    {
        public int Id { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public int UserId { get; set; }
        public int UserRoleId { get; set; }
        public int UserLoginStateId { get; set; }
    
        public virtual UserLoginStates UserLoginStates { get; set; }
        public virtual UserRoles UserRoles { get; set; }
        public virtual Users Users { get; set; }
    }
}
